box_ids = [
	'auxwcbzrmdvpsjfgkrthnkioqm',
	'auxwcbzrmdvpsjfgbltonyijqe',
	'auxwcbzrmdfpsefgklthnoioqe',
	'auxwcbzrmdvpsjfgkluhnjisqe',
	'auxwcbzrmdvesjfgdzthnyioqe',
	'auxwcbzrmdvhsjfgklthnmijqe',
	'auxwcbzridvpsjfgkltxeyioqe',
	'ayxwcbzrgdvpsjfgklthiyioqe',
	'ajxwcbzrmdvpsjfgklkhnyiode',
	'auxwcbcrmdvpsjfqelthnyioqe',
	'auxwcbzrmsvpsjsgklthnyiope',
	'auxwcbzrmqvpsjzgklghnyioqe',
	'auxwcbzrmdvpsjtqklthxyioqe',
	'auxwcbzrmdopsjfdklthncioqe',
	'auxwcbzrmdvpsjfgkltmhyfoqe',
	'aixwcbzrmdvpsjfgllthdyeoqe',
	'vuxicbzrmdepsjfgklthnyioqe',
	'auxwcbbxmdkpsjfgklthnyioqe',
	'auxwcbzrgdvpsofaklthnyioqe',
	'auxycbzrmdvpsjfgklthnyuose',
	'aujwcbzrmdvprjfgkltcnyioqe',
	'auxwgbzrmdvpsjfgyzthnyioqe',
	'auxwcbzrmavpsjfgkltsnyiome',
	'auxwcbgrmdvpsjfgkdthnrioqe',
	'kuxwcbzrmdvpsyfgklthnyioue',
	'auxwcbzomdvpjdfgklthnyioqe',
	'auxwcbzrmdppsjfgklthvyifqe',
	'aunwubzrmdvpsjrgklthnyioqe',
	'auxwcbzrmoipsjfgklbhnyioqe',
	'auxwdbzrmdvpsjfgmlthnyioce',
	'auxwcbzjmsvpsjfiklthnyioqe',
	'auxwcbzrmwcpsjfcklthnyioqe',
	'auxwcbzfmdvprjfhklthnyioqe',
	'auxdcbzrgdvpsjfgklthnyxoqe',
	'wuxwbbzrmdvpsjfgklthnyiote',
	'auowcbjrmdvpsjfgklthnyfoqe',
	'auxwsbzrmdvpsjfglltcnyioqe',
	'quxwcbzrmdvpkjfgklthnyioqt',
	'vuxwcbzrudvpsjfgklthnyioqi',
	'puxwcbzrmdvgsjfgklthncioqe',
	'luxdcbzrmdvpsjfgkothnyioqe',
	'auxwcbzrmdvpsjfyklthfhioqe',
	'auxwcbqrmdvpsjfgkldhnyiote',
	'quxwcbzrmlvpsjfgklthnyioqi',
	'auxwcbzgmdvpsjfoklthnyiuqe',
	'auxwcbzrmdvpsbfgkltdjyioqe',
	'auxwcbzsmdrpsjfgklthpyioqe',
	'auxwcbzrmfvpsjfwklthnyiote',
	'auxbkpzrmdvpsjfgklthnyioqe',
	'auxwcbzrddvpsjfsklthnyroqe',
	'abxwcbzrmdvpsjfgkltdnyivqe',
	'awxwcbzrmvvpsjfgklthngioqe',
	'auxwcbzrmkvgsjfgkltcnyioqe',
	'auxwcbammdvpsjfgklthpyioqe',
	'auxwcbhrmdvpsjfgtlthnuioqe',
	'auxwcpzrmdvpbjogklthnyioqe',
	'auxwcbzrmdvpslfgklbhkyioqe',
	'auxwcbsrmdvpjjfgkldhnyioqe',
	'auxwcbzrmdqpsjfgauthnyioqe',
	'ydxwcbxrmdvpsjfgklthnyioqe',
	'auxwcbzrmdvpejfgklthnyyofe',
	'auxwchzrmxvpsjfgklthnyioqh',
	'auxwcbzrtdvpsjfgklxhnzioqe',
	'auxwcbyrmdvpsnfgklnhnyioqe',
	'auxwcbzrcdvpsjugklihnyioqe',
	'auxwcbzrddvpsjfgklhhnyiaqe',
	'aumwtbzrmdvpsjfgklthnyitqe',
	'auxucbzrmdvpsjfgklthwfioqe',
	'auxwcbzrmdvpzmfgkllhnyioqe',
	'auxwcbzrmdvpsjhgklthntiome',
	'buxwzbzrmdvpszfgklthnyioqe',
	'ouxwcbzsgdvpsjfgklthnyioqe',
	'auxwcbzrmdvpsjfskltgnyioqz',
	'auxwcbbrmdvpsjftklthnyioqu',
	'quxocbzrmdvpsjfgklthfyioqe',
	'acxwcbzrmdvpsjfgklfhnrioqe',
	'auxwcbzrmdnpsjfrkjthnyioqe',
	'wuxwybzrmdwpsjfgklthnyioqe',
	'auxwgbxrmdvpsjfghlthnyioqe',
	'atxwcbzrmdvnsjfgklthnyjoqe',
	'acxwcbzmmdvpsjfbklthnyioqe',
	'auxhcbzrmdvbsjbgklthnyioqe',
	'auxwlbzrfdvpsjfgxlthnyioqe',
	'auxwmbzrmdfpsjqgklthnyioqe',
	'auxwcbzrmdvpsgfgklahnyigqe',
	'auxwgbzrmdvpsjfgzldhnyioqe',
	'auxwcbzrmdvpydfgklthnyiohe',
	'auxwxbzrmdvpsjfsklchnyioqe',
	'auxqcbzrmdvpsjfgqlthnyiwqe',
	'auxwcozrmdvssbfgklthnyioqe',
	'auxvcczrmdvpsufgklthnyioqe',
	'auxwcbzrudvpsjfgklyhnyioxe',
	'aulwcbzrmdvpsjqgknthnyioqe',
	'auukcbzrmdvpsjfgklthtyioqe',
	'auxwcszimdvpsjfgklthnyigqe',
	'juxwcbzrbdvpsjfgklthnyboqe',
	'auxwcbzrmdvpjofgklthnyioqj',
	'auxwcbzrmdvpsjfgplfhnyione',
	'auxwcbzrmdhpsjfgkltknyeoqe',
	'luxwcqzrmdvpsjfgklthnbioqe',
	'uuxwcbzrmdvpsjfgkithnyiiqe',
	'auxwcbzrmdvpdjfgkrthnyeoqe',
	'auuwcbnrmdvpsjfgklthnjioqe',
	'auxwcnzrmdvpsjvgklthnyooqe',
	'auxwcbzcmdvpsjfcklthnyiose',
	'auxwcbzrldfpsjfgklthjyioqe',
	'auxwcizrmdvpsjfjklthnymoqe',
	'auxwcbtrmdvpsjfgtlphnyioqe',
	'amxwcbzrmdvksjfgklthnyiove',
	'auxwcbzrmdvpszfgkpthnyiuqe',
	'auxwcbzrmdvxdjfgkltqnyioqe',
	'auxwcbzrudvpsjfgklthnymiqe',
	'auxwcbirmdvfsjfgklmhnyioqe',
	'auwwcbzrndvprjfgklthnyioqe',
	'auxwcbormdgpsjfgklbhnyioqe',
	'auxwabzrmdupsjfgklthnyioqt',
	'auxvcbzrmdvpsjfgkltrmyioqe',
	'auxwcbzrmddpsjfsklthnyizqe',
	'auxwcczrmuvpyjfgklthnyioqe',
	'auxwcczrmdvpsnfgkpthnyioqe',
	'auxkcbzrmdvpsjfhklihnyioqe',
	'auxwcbzrmdvpsjfgklthnkijje',
	'auxwcbzcmdvpsjpgkldhnyioqe',
	'auxwcnzrudvpstfgklthnyioqe',
	'xuxwcbzrgdvusjfgklthnyioqe',
	'aaxwcbzrmdvpsjvgklthnyidqe',
	'auxwcbztmdvpsjfgklthnyhqqe',
	'auxwcbzrmfvpsjfgklthnyilfe',
	'auxwcbzrmdvksjfgklthjyioqq',
	'auxwcbzrmdzksjfgktthnyioqe',
	'auxwcbzrmfvpszfgklohnyioqe',
	'auxwckzamdvpsjfgklthnyioqs',
	'auxwcmzrhdvpsjfaklthnyioqe',
	'fuxwcbzrmdapsjfgklrhnyioqe',
	'avxwxbzrmdvpsjfgklthniioqe',
	'auxwubzrmevpsjfgkltpnyioqe',
	'fuxwcbzrgdvpsjfgklhhnyioqe',
	'duxwwbdrmdvpsjfgklthnyioqe',
	'audwcbzrmdvpnjcgklthnyioqe',
	'auxtcbzrmdvpsjmgklthnyyoqe',
	'aucwcbwrmdepsjfgklthnyioqe',
	'auxwcbzrudvpsjfpklthnyiose',
	'auxwcbzridvpsjfsklthxyioqe',
	'auxtcbzrmdvpscfgklyhnyioqe',
	'auxwcbzrmdvppjfgklthnyivee',
	'auxwdbzrmuvpskfgklthnyioqe',
	'auxwubzrmdvosjfgklthnyiope',
	'auxwcbzrmhnpsjfgklthnyimqe',
	'auxwcbzrmdqpwjfgkltpnyioqe',
	'auxwcbormdvpsjljklthnyioqe',
	'auxwcbzrmdjpsjfgkltjpyioqe',
	'auxwcbzrmdvpszfgklthkyizqe',
	'auxwcbzighvpsjfgklthnyioqe',
	'auxwcbzrmdlpsjfgcythnyioqe',
	'auxwcbzumdvpsjflklthnyimqe',
	'pdxwcbzrmdvpsjfgklthnyihqe',
	'auxwcbzrsdvpsjfgklhhvyioqe',
	'auxwcfzamdvpsjfgkmthnyioqe',
	'aexwcdzrmdvpsjogklthnyioqe',
	'auxxcbkrmavpsjfgklthnyioqe',
	'auxwcbzredvssjfgklthryioqe',
	'aupwqbzrmdvpsjfgklthnyioqc',
	'auxwcbzrmdvpkcagklthnyioqe',
	'auxwcbzrmdvwsbfgklthnlioqe',
	'aunwcbzxmdvhsjfgklthnyioqe',
	'auxwcbzrhddpsjfgklthnnioqe',
	'ouxwcbzrmdvtsifgklthnyioqe',
	'auxwcbzrmdqpsjfgklthnyfoqp',
	'auxwrbzrhdvpsjfgolthnyioqe',
	'auxwcbcqmdvpsjugklthnyioqe',
	'auxwcbzrqdvpsjhgklthnjioqe',
	'auxmcbzrmdvpsjfgmlthnyjoqe',
	'auxwcbzrmdvpsjfgzlthnycoqv',
	'auswcbzrmdvpsffgslthnyioqe',
	'auxwcbzrfdvpsjfrmlthnyioqe',
	'auxwcbzrmdvpsjngzlthnxioqe',
	'auxwcbzrmdvpsjfuqlthnyiyqe',
	'auxwzbzrrdvosjfgklthnyioqe',
	'auxwcbzdmdvpsjfikxthnyioqe',
	'guxwcbzrmdvpsjfgmlthnytoqe',
	'auxwcbzrmdvpspfgkytenyioqe',
	'auxvcbzrldvpsjfgklthnyhoqe',
	'auxwcbzrmavpckfgklthnyioqe',
	'autwcbzrmdvpsafgklthnyirqe',
	'auxwcbzrxuvpsjfgklthmyioqe',
	'auxwcbarmdppsjfgklthnywoqe',
	'anxvcbzrmdvpsjfgklthnyijqe',
	'auxwcbwrmdapsjngklthnyioqe',
	'abxwcbzrmdvpsjugkltgnyioqe',
	'auxwcbtrmdvpsjfgkltunyioue',
	'aujwcbzrmovpsjfgklthryioqe',
	'auxwcbzrydvpsjfgklthndikqe',
	'auxwcbzrmdvpsjfgklmrnyioqo',
	'auxwcbzrddvpsjfggithnyioqe',
	'auxwcbzrmdvpfjfaklthlyioqe',
	'fuxtcbzrmdvpsjfgklwhnyioqe',
	'tuxwcbzrjdvpsjfgjlthnyioqe',
	'auxwcbzrmdppsofgklthnyfoqe',
	'auxvclzamdvpsjfgklthnyioqe',
	'auxwcbzrmdvpsjfdklhhnzioqe',
	'auxwcbzrmsvpsvdgklthnyioqe',
	'arxfcbzrmdvpsvfgklthnyioqe',
	'auxzcbzrmdvpsjfgklthnhioqj',
	'auxwcbzrrdvpsjfgpltunyioqe',
	'auxuibzrmdvpwjfgklthnyioqe',
	'auxwcbzrwdqpsjfgklthnyooqe',
	'aujwcbzrmdvpsjvgklthxyioqe',
	'abxwcbzrmfvpsjfgklthnyxoqe',
	'aurwcbzrmdvpshfgklthnyhoqe',
	'auxwcbzjmdvpsjfgknthnycoqe',
	'auxwcbzrmdvpsjfgklmhxwioqe',
	'auxwcbzrmfvpsjfgklthnyiorq',
	'auxwcbormdvpsjfgklwhnlioqe',
	'auxwctzrmdvpsjfgklcknyioqe',
	'awxwcbzrmdvpsjfgvlthnyiome',
	'auxwcbzrmdvpsjfjklthnyixje',
	'auxwcsxrmdvpsjfgkltsnyioqe',
	'auxbmbzrmdvpsjfgklthnyioce',
	'auxwcbzrmdvpsjfukzthnytoqe',
	'aixwcbzrmdvpsjfgllthdyioqe',
	'auxwcbzrmdypsjfgklthnlioqy',
	'auxccbzrmdvpsjfgkltrnnioqe',
	'auxwcznrmdvpsjfgklthnykoqe',
	'auxwmqzrmdvpsjfgilthnyioqe',
	'auxwcbzrmdvpdyfgolthnyioqe',
	'auxwcbzrmdvpsjfgkmohnqioqe',
	'auxwcfzrmzvpsjfoklthnyioqe',
	'auxwjyzrmdvpsjfgulthnyioqe',
	'auxwcgzredvpsjfgkxthnyioqe',
	'wuxwcbtrmdvpsjfgklthnyiofe',
	'auxwcbzrmdopsgfgklthncioqe',
	'auxmcbzjmdvpsjfgklbhnyioqe',
	'auxwlbzrmdvpsjffklthgyioqe',
	'auxwcbzrmrvpsjfgqlthtyioqe',
	'kuxwhbzrmdvpsjfgklthgyioqe',
	'auxwcozrmdgpsjfgklthnydoqe',
	'auxwdbzrmdvpdjfgklthgyioqe',
	'auxwqbzrmdapsvfgklthnyioqe',
	'auqwcbzridvjsjfgklthnyioqe',
	'auxwckzrmdvpsjfoklthnyuoqe',
	'auxwcbzvmdvpsjfgklghnyiome',
	'auxtcbzrmdvpsjqgktthnyioqe',
	'auxwcbzrmdvesjfgkljhnnioqe',
	'auxwcbzrmpvpsqfgklthnqioqe',
	'auxwcbzrmdcpsqfgklthnzioqe',
	'yuxwcbzrmdvpsjggklthnlioqe',
	'auxwcbzradvpsjftklthoyioqe',
	'auxwcbzrmdvjujfgklmhnyioqe',
	'auxwcbzrmdvpsrfgklpinyioqe',
	'auxwobzrvqvpsjfgklthnyioqe'
]


from multiprocessing import Pool
from itertools import combinations
from time import time

def compare_ids(ids):
	id1 = ids[0]
	id2 = ids[1]
	differences = 0
	return_string = ''

	for index, char1 in enumerate(list(id1)):
		char2 = id2[index]

		if char1 == char2:
			return_string += char1
		else:
			differences += 1

		if differences > 1:
			return

	return return_string

if __name__ == '__main__':
	start_time = time()

	box_ids.sort()

	process_pool = Pool(4)
	comparisons = process_pool.map(compare_ids, combinations(box_ids, 2))

	for result in comparisons:
		if result:
			print(result)

	print('Finished in', time() - start_time)
